# Generated by Django 2.2.2 on 2019-07-24 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_attendance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentinfo',
            unique_together={('admission_id', 'class_type')},
        ),
    ]
